"""07 production

Revision ID: 023c018ffd88
Revises: 1e50772d45e6
Create Date: 2026-10-03 23:00:20.852399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '023c018ffd88'
down_revision: Union[str, Sequence[str], None] = '1e50772d45e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_AssemblyOps',
    sa.Column('AssemblyOp_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AssemblyOp_Code', sa.String(length=20), nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=False),
    sa.Column('Operation_Name', sa.Unicode(length=100), nullable=False),
    sa.Column('Activity_ID', sa.Integer(), nullable=True),
    sa.Column('Operation_Type', sa.String(length=6), server_default='OWN', nullable=False),
    sa.Column('Workers_Per_Cell', sa.Numeric(precision=5, scale=2), server_default='1', nullable=False),
    sa.Column('Units_Per_Hour', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('Sec_Per_Unit', sa.Numeric(precision=10, scale=3), sa.Computed('CAST(3600.0 / Units_Per_Hour AS NUMERIC(10, 3))', persisted=True), nullable=False),
    sa.Column('Labor_Hrs_Per_Unit', sa.Numeric(precision=12, scale=6), sa.Computed('CAST(Workers_Per_Cell / Units_Per_Hour AS NUMERIC(12, 6))', persisted=True), nullable=False),
    sa.Column('Sequence', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Operation_Type IN ('OWN','FASON')", name=op.f('CK_tbl_AssemblyOps_operation_type')),
    sa.CheckConstraint('Units_Per_Hour > 0', name=op.f('CK_tbl_AssemblyOps_units')),
    sa.CheckConstraint('Workers_Per_Cell > 0', name=op.f('CK_tbl_AssemblyOps_workers')),
    sa.ForeignKeyConstraint(['Activity_ID'], ['tbl_Activities.Activity_ID'], name=op.f('FK_tbl_AssemblyOps_Activity_ID')),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_AssemblyOps_Item_ID')),
    sa.PrimaryKeyConstraint('AssemblyOp_ID', name=op.f('PK_tbl_AssemblyOps')),
    sa.UniqueConstraint('AssemblyOp_Code', name=op.f('UQ_tbl_AssemblyOps_AssemblyOp_Code'))
    )
    op.create_index(op.f('IX_tbl_AssemblyOps_Item_ID'), 'tbl_AssemblyOps', ['Item_ID'], unique=False)
    op.create_table('tbl_Moulds',
    sa.Column('Mould_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Mould_Code', sa.String(length=20), nullable=False),
    sa.Column('Mould_Name', sa.Unicode(length=100), nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=True),
    sa.Column('Mould_Owner', sa.String(length=10), server_default='LAMAPLAST', nullable=False),
    sa.Column('Customer_ID', sa.Integer(), nullable=True),
    sa.Column('Mould_Type', sa.String(length=12), server_default='SINGLE', nullable=False),
    sa.Column('Cavities', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('Default_Machine_Category', sa.String(length=5), nullable=True),
    sa.Column('Acquisition_Cost_EUR', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('Residual_Value_EUR', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('Depreciable_Value_EUR', sa.Numeric(precision=12, scale=2), sa.Computed('CAST(Acquisition_Cost_EUR - Residual_Value_EUR AS NUMERIC(12, 2))', persisted=True), nullable=False),
    sa.Column('Life_Cycles', sa.Integer(), nullable=True),
    sa.Column('Current_Cycles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('Wear_Pct', sa.Numeric(precision=7, scale=4), sa.Computed('CAST(CAST(Current_Cycles AS DECIMAL(14,4)) / NULLIF(Life_Cycles, 0) AS NUMERIC(7, 4))', persisted=True), nullable=True),
    sa.Column('Depreciation_Per_Cycle', sa.Numeric(precision=12, scale=6), sa.Computed('CAST((Acquisition_Cost_EUR - Residual_Value_EUR) / NULLIF(Life_Cycles, 0) AS NUMERIC(12, 6))', persisted=True), nullable=True),
    sa.Column('QC_Factor', sa.SmallInteger(), server_default='2', nullable=False),
    sa.Column('Technicians', sa.SmallInteger(), nullable=True),
    sa.Column('Year_Constructed', sa.SmallInteger(), nullable=True),
    sa.Column('Replacement_Estimate', sa.Date(), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Mould_Owner IN ('LAMAPLAST','CUSTOMER')", name=op.f('CK_tbl_Moulds_owner')),
    sa.CheckConstraint("Mould_Type IN ('SINGLE','MULTI_CAVITY','FAMILY')", name=op.f('CK_tbl_Moulds_mould_type')),
    sa.CheckConstraint('Cavities >= 1', name=op.f('CK_tbl_Moulds_cavities')),
    sa.CheckConstraint('QC_Factor BETWEEN 1 AND 3', name=op.f('CK_tbl_Moulds_qc_factor')),
    sa.CheckConstraint('Residual_Value_EUR <= Acquisition_Cost_EUR', name=op.f('CK_tbl_Moulds_residual')),
    sa.ForeignKeyConstraint(['Customer_ID'], ['tbl_Customers.Customer_ID'], name=op.f('FK_tbl_Moulds_Customer_ID')),
    sa.ForeignKeyConstraint(['Default_Machine_Category'], ['tbl_MachineCategories.Category_Code'], name=op.f('FK_tbl_Moulds_Default_Machine_Category')),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_Moulds_Item_ID')),
    sa.PrimaryKeyConstraint('Mould_ID', name=op.f('PK_tbl_Moulds')),
    sa.UniqueConstraint('Mould_Code', name=op.f('UQ_tbl_Moulds_Mould_Code'))
    )
    op.create_table('tbl_MouldRuns',
    sa.Column('MouldRun_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MouldRun_Code', sa.String(length=20), nullable=False),
    sa.Column('Mould_ID', sa.Integer(), nullable=False),
    sa.Column('Machine_Category', sa.String(length=5), nullable=False),
    sa.Column('Cycles_Per_Hour', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('Sec_Per_Cycle', sa.Numeric(precision=10, scale=3), sa.Computed('CAST(3600.0 / Cycles_Per_Hour AS NUMERIC(10, 3))', persisted=True), nullable=False),
    sa.Column('Operator_Load_Factor', sa.Numeric(precision=4, scale=2), server_default='1', nullable=False),
    sa.Column('Sprue_Runner_Total_g', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('Scrap_Pct', sa.Numeric(precision=5, scale=4), server_default='0.041', nullable=False),
    sa.Column('Regrind_Recovery_Override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Max_Regrind_In_Mix_Pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Setup_Min', sa.Numeric(precision=6, scale=1), server_default='41', nullable=False),
    sa.Column('Setdown_Min', sa.Numeric(precision=6, scale=1), server_default='22', nullable=False),
    sa.Column('Avg_Batch_Qty', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('QC_Hours_Per_Batch', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Avg_Batch_Qty IS NULL OR Avg_Batch_Qty > 0', name=op.f('CK_tbl_MouldRuns_batch')),
    sa.CheckConstraint('Cycles_Per_Hour > 0', name=op.f('CK_tbl_MouldRuns_cycles')),
    sa.CheckConstraint('Operator_Load_Factor IN (0.33,0.5,1.0,2.0)', name=op.f('CK_tbl_MouldRuns_operator_load')),
    sa.CheckConstraint('Scrap_Pct BETWEEN 0 AND 1', name=op.f('CK_tbl_MouldRuns_scrap')),
    sa.ForeignKeyConstraint(['Machine_Category'], ['tbl_MachineCategories.Category_Code'], name=op.f('FK_tbl_MouldRuns_Machine_Category')),
    sa.ForeignKeyConstraint(['Mould_ID'], ['tbl_Moulds.Mould_ID'], name=op.f('FK_tbl_MouldRuns_Mould_ID')),
    sa.PrimaryKeyConstraint('MouldRun_ID', name=op.f('PK_tbl_MouldRuns')),
    sa.UniqueConstraint('MouldRun_Code', name=op.f('UQ_tbl_MouldRuns_MouldRun_Code')),
    sa.UniqueConstraint('Mould_ID', 'Machine_Category', name=op.f('UQ_tbl_MouldRuns_Mould_ID'))
    )
    op.create_index(op.f('IX_tbl_MouldRuns_Mould_ID'), 'tbl_MouldRuns', ['Mould_ID'], unique=False)
    op.create_table('tbl_MouldRunMaterials',
    sa.Column('MouldRun_ID', sa.Integer(), nullable=False),
    sa.Column('Material_Item_ID', sa.Integer(), nullable=False),
    sa.Column('Material_Type', sa.String(length=12), server_default='BASE_RESIN', nullable=False),
    sa.Column('Mix_Pct', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('Is_Regrind_Source', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Regrind_Value_Override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Sequence', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Material_Type IN ('BASE_RESIN','MASTERBATCH','ADDITIVE','FILLER')", name=op.f('CK_tbl_MouldRunMaterials_material_type')),
    sa.CheckConstraint('Mix_Pct > 0 AND Mix_Pct <= 1', name=op.f('CK_tbl_MouldRunMaterials_mix')),
    sa.ForeignKeyConstraint(['Material_Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_MouldRunMaterials_Material_Item_ID')),
    sa.ForeignKeyConstraint(['MouldRun_ID'], ['tbl_MouldRuns.MouldRun_ID'], name=op.f('FK_tbl_MouldRunMaterials_MouldRun_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MouldRun_ID', 'Material_Item_ID', name=op.f('PK_tbl_MouldRunMaterials'))
    )
    op.create_index(op.f('IX_tbl_MouldRunMaterials_Material_Item_ID'), 'tbl_MouldRunMaterials', ['Material_Item_ID'], unique=False)
    op.create_table('tbl_MouldRunOutputs',
    sa.Column('MouldRun_ID', sa.Integer(), nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=False),
    sa.Column('Pieces_Per_Cycle', sa.SmallInteger(), nullable=False),
    sa.Column('Net_Part_Weight_g', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('Cost_Share_Pct', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('Is_Default', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Cost_Share_Pct IS NULL OR Cost_Share_Pct BETWEEN 0 AND 1', name=op.f('CK_tbl_MouldRunOutputs_share')),
    sa.CheckConstraint('Net_Part_Weight_g > 0', name=op.f('CK_tbl_MouldRunOutputs_weight')),
    sa.CheckConstraint('Pieces_Per_Cycle >= 1', name=op.f('CK_tbl_MouldRunOutputs_pieces')),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_MouldRunOutputs_Item_ID')),
    sa.ForeignKeyConstraint(['MouldRun_ID'], ['tbl_MouldRuns.MouldRun_ID'], name=op.f('FK_tbl_MouldRunOutputs_MouldRun_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MouldRun_ID', 'Item_ID', name=op.f('PK_tbl_MouldRunOutputs'))
    )
    op.create_index(op.f('IX_tbl_MouldRunOutputs_Item_ID'), 'tbl_MouldRunOutputs', ['Item_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_MouldRunOutputs_Item_ID'), table_name='tbl_MouldRunOutputs')
    op.drop_table('tbl_MouldRunOutputs')
    op.drop_index(op.f('IX_tbl_MouldRunMaterials_Material_Item_ID'), table_name='tbl_MouldRunMaterials')
    op.drop_table('tbl_MouldRunMaterials')
    op.drop_index(op.f('IX_tbl_MouldRuns_Mould_ID'), table_name='tbl_MouldRuns')
    op.drop_table('tbl_MouldRuns')
    op.drop_table('tbl_Moulds')
    op.drop_index(op.f('IX_tbl_AssemblyOps_Item_ID'), table_name='tbl_AssemblyOps')
    op.drop_table('tbl_AssemblyOps')
    # ### end Alembic commands ###
