"""05 scenarios

Revision ID: 15647a552bd4
Revises: 98e5275731c4
Create Date: 2026-10-03 22:39:41.907050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '15647a552bd4'
down_revision: Union[str, Sequence[str], None] = '98e5275731c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Scenarios',
    sa.Column('Scenario_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Scenario_Name', sa.Unicode(length=60), nullable=False),
    sa.Column('Scenario_Type', sa.String(length=10), nullable=False),
    sa.Column('Base_Scenario_ID', sa.Integer(), nullable=True),
    sa.Column('Period_Year', sa.SmallInteger(), nullable=False),
    sa.Column('Owner_User_ID', sa.Integer(), nullable=True),
    sa.Column('Is_Locked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Is_Baseline', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Locked_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Locked_By', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Scenario_Type IN ('BUDGET','ACTUAL','REVISED','WHATIF')", name='scenario_type'),
    sa.CheckConstraint('Base_Scenario_ID IS NULL OR Base_Scenario_ID <> Scenario_ID', name='base_not_self'),
    sa.ForeignKeyConstraint(['Base_Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_Scenarios_Base_Scenario_ID')),
    sa.ForeignKeyConstraint(['Owner_User_ID'], ['tbl_Users.User_ID'], name=op.f('FK_tbl_Scenarios_Owner_User_ID')),
    sa.PrimaryKeyConstraint('Scenario_ID', name=op.f('PK_tbl_Scenarios')),
    sa.UniqueConstraint('Scenario_Name', name=op.f('UQ_tbl_Scenarios_Scenario_Name'))
    )
    op.create_index(op.f('IX_tbl_Scenarios_Owner_User_ID'), 'tbl_Scenarios', ['Owner_User_ID'], unique=False)
    op.create_index('UX_tbl_Scenarios_one_baseline', 'tbl_Scenarios', ['Is_Baseline'], unique=True, mssql_where=sa.text('Is_Baseline = 1'))
    op.create_table('tbl_ScenarioOverrides',
    sa.Column('Override_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Target_Type', sa.String(length=10), nullable=False),
    sa.Column('Target_ID', sa.Integer(), nullable=False),
    sa.Column('Field_Name', sa.String(length=40), nullable=False),
    sa.Column('Value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('Reason', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Field_Name IN ('Cycles_Per_Hour','Scrap_Pct','Avg_Batch_Qty','Depreciation_Per_Cycle','Depreciation_Per_Hour','Power_KW','Weight_kg')", name='field_name'),
    sa.CheckConstraint("Target_Type IN ('ITEM','MOULD_RUN','MOULD','MACHINE')", name='target_type'),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_ScenarioOverrides_Scenario_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Override_ID', name=op.f('PK_tbl_ScenarioOverrides')),
    sa.UniqueConstraint('Scenario_ID', 'Target_Type', 'Target_ID', 'Field_Name', name=op.f('UQ_tbl_ScenarioOverrides_Scenario_ID'))
    )
    op.create_table('tbl_ScenarioParameters',
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Parameter', sa.String(length=50), nullable=False),
    sa.Column('Value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('Reason', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Parameter'], ['tbl_GlobalDefault.Parameter'], name=op.f('FK_tbl_ScenarioParameters_Parameter')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_ScenarioParameters_Scenario_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Scenario_ID', 'Parameter', name=op.f('PK_tbl_ScenarioParameters'))
    )
    op.create_table('tbl_ItemVolumes',
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=False),
    sa.Column('Annual_Qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('Source', sa.String(length=12), server_default='MANUAL', nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Annual_Qty >= 0', name='qty'),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_ItemVolumes_Item_ID')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_ItemVolumes_Scenario_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Scenario_ID', 'Item_ID', name=op.f('PK_tbl_ItemVolumes'))
    )
    op.create_table('tbl_Prices',
    sa.Column('Price_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=False),
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Valid_From', sa.Date(), nullable=False),
    sa.Column('Valid_To', sa.Date(), nullable=True),
    sa.Column('Price_EUR', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('Currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('FX_Rate', sa.Numeric(precision=12, scale=6), server_default=sa.text('1'), nullable=False),
    sa.Column('Price_Local', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('Supplier', sa.Unicode(length=100), nullable=True),
    sa.Column('Source', sa.String(length=12), server_default='MANUAL', nullable=False),
    sa.Column('Reason', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Source IN ('MANUAL','SOFTONE','EXCEL','CALCULATED')", name='source'),
    sa.CheckConstraint('Price_EUR >= 0', name='price_positive'),
    sa.CheckConstraint('Valid_To IS NULL OR Valid_To >= Valid_From', name='valid_range'),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_Prices_Item_ID')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_Prices_Scenario_ID')),
    sa.PrimaryKeyConstraint('Price_ID', name=op.f('PK_tbl_Prices')),
    sa.UniqueConstraint('Item_ID', 'Scenario_ID', 'Valid_From', name=op.f('UQ_tbl_Prices_Item_ID'))
    )
    op.create_index(op.f('IX_tbl_Prices_Item_ID'), 'tbl_Prices', ['Item_ID'], unique=False)
    op.create_index(op.f('IX_tbl_Prices_Scenario_ID'), 'tbl_Prices', ['Scenario_ID'], unique=False)
    op.create_table('tbl_SalesPrices',
    sa.Column('Sales_Price_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=False),
    sa.Column('Customer_ID', sa.Integer(), nullable=True),
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Valid_From', sa.Date(), nullable=False),
    sa.Column('Valid_To', sa.Date(), nullable=True),
    sa.Column('Price_EUR', sa.Numeric(precision=14, scale=5), nullable=False),
    sa.Column('Source', sa.String(length=12), server_default='MANUAL', nullable=False),
    sa.Column('Reason', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Source IN ('MANUAL','SOFTONE','EXCEL','CALCULATED')", name='source'),
    sa.CheckConstraint('Price_EUR >= 0', name='price_positive'),
    sa.CheckConstraint('Valid_To IS NULL OR Valid_To >= Valid_From', name='valid_range'),
    sa.ForeignKeyConstraint(['Customer_ID'], ['tbl_Customers.Customer_ID'], name=op.f('FK_tbl_SalesPrices_Customer_ID')),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_SalesPrices_Item_ID')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_SalesPrices_Scenario_ID')),
    sa.PrimaryKeyConstraint('Sales_Price_ID', name=op.f('PK_tbl_SalesPrices')),
    sa.UniqueConstraint('Item_ID', 'Customer_ID', 'Scenario_ID', 'Valid_From', name=op.f('UQ_tbl_SalesPrices_Item_ID'))
    )
    op.create_index(op.f('IX_tbl_SalesPrices_Item_ID'), 'tbl_SalesPrices', ['Item_ID'], unique=False)
    op.create_index(op.f('IX_tbl_SalesPrices_Scenario_ID'), 'tbl_SalesPrices', ['Scenario_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_SalesPrices_Scenario_ID'), table_name='tbl_SalesPrices')
    op.drop_index(op.f('IX_tbl_SalesPrices_Item_ID'), table_name='tbl_SalesPrices')
    op.drop_table('tbl_SalesPrices')
    op.drop_index(op.f('IX_tbl_Prices_Scenario_ID'), table_name='tbl_Prices')
    op.drop_index(op.f('IX_tbl_Prices_Item_ID'), table_name='tbl_Prices')
    op.drop_table('tbl_Prices')
    op.drop_table('tbl_ItemVolumes')
    op.drop_table('tbl_ScenarioParameters')
    op.drop_table('tbl_ScenarioOverrides')
    op.drop_index('UX_tbl_Scenarios_one_baseline', table_name='tbl_Scenarios', mssql_where=sa.text('Is_Baseline = 1'))
    op.drop_index(op.f('IX_tbl_Scenarios_Owner_User_ID'), table_name='tbl_Scenarios')
    op.drop_table('tbl_Scenarios')
    # ### end Alembic commands ###
