"""06 resources

Revision ID: 1e50772d45e6
Revises: 15647a552bd4
Create Date: 2026-10-03 22:46:32.740488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1e50772d45e6'
down_revision: Union[str, Sequence[str], None] = '15647a552bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Resources',
    sa.Column('Resource_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Resource_Code', sa.String(length=20), nullable=False),
    sa.Column('Resource_Name', sa.Unicode(length=80), nullable=False),
    sa.Column('CC_ID', sa.SmallInteger(), nullable=False),
    sa.Column('Resource_Type', sa.String(length=12), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Resource_Type IN ('LABOR','MACHINE','BUILDING','OVERHEAD','COMMERCIAL','ADMIN')", name=op.f('CK_tbl_Resources_resource_type')),
    sa.ForeignKeyConstraint(['CC_ID'], ['tbl_CostCenters.CC_ID'], name=op.f('FK_tbl_Resources_CC_ID')),
    sa.PrimaryKeyConstraint('Resource_ID', name=op.f('PK_tbl_Resources')),
    sa.UniqueConstraint('Resource_Code', name=op.f('UQ_tbl_Resources_Resource_Code'))
    )
    op.create_index(op.f('IX_tbl_Resources_CC_ID'), 'tbl_Resources', ['CC_ID'], unique=False)
    op.create_table('tbl_Buildings',
    sa.Column('Building_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Building_Code', sa.Unicode(length=15), nullable=False),
    sa.Column('Zone_Name', sa.Unicode(length=40), nullable=True),
    sa.Column('Ownership', sa.Unicode(length=15), server_default='ΙΔΙΟΚΤΗΤΟ', nullable=False),
    sa.Column('Floor_Level', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('Area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('Utilization_Pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Nominal_Volume_m3', sa.Numeric(precision=14, scale=2), sa.Computed('CAST(Area_m2 * Height_m AS NUMERIC(14, 2))', persisted=True), nullable=True),
    sa.Column('Useful_Volume_m3', sa.Numeric(precision=14, scale=2), sa.Computed('CAST(Area_m2 * Height_m * Utilization_Pct AS NUMERIC(14, 2))', persisted=True), nullable=True),
    sa.Column('Cost_Basis', sa.String(length=3), server_default='m2', nullable=False),
    sa.Column('CC_ID', sa.SmallInteger(), nullable=False),
    sa.Column('Resource_ID', sa.Integer(), nullable=True),
    sa.Column('Depreciation_EUR', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('Equipment_Depr_EUR', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('IT_Depr_EUR', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('Total_Cost_EUR', sa.Numeric(precision=14, scale=2), sa.Computed('CAST(Depreciation_EUR + Equipment_Depr_EUR + IT_Depr_EUR AS NUMERIC(14, 2))', persisted=True), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Cost_Basis IN ('m2','m3')", name=op.f('CK_tbl_Buildings_cost_basis')),
    sa.CheckConstraint('Utilization_Pct IS NULL OR Utilization_Pct BETWEEN 0 AND 1', name=op.f('CK_tbl_Buildings_utilization')),
    sa.ForeignKeyConstraint(['CC_ID'], ['tbl_CostCenters.CC_ID'], name=op.f('FK_tbl_Buildings_CC_ID')),
    sa.ForeignKeyConstraint(['Resource_ID'], ['tbl_Resources.Resource_ID'], name=op.f('FK_tbl_Buildings_Resource_ID')),
    sa.PrimaryKeyConstraint('Building_ID', name=op.f('PK_tbl_Buildings')),
    sa.UniqueConstraint('Building_Code', 'Zone_Name', name=op.f('UQ_tbl_Buildings_Building_Code'))
    )
    op.create_index(op.f('IX_tbl_Buildings_CC_ID'), 'tbl_Buildings', ['CC_ID'], unique=False)
    op.create_index(op.f('IX_tbl_Buildings_Resource_ID'), 'tbl_Buildings', ['Resource_ID'], unique=False)
    op.create_table('tbl_LaborResources',
    sa.Column('Employee_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Employee_Code', sa.String(length=15), nullable=False),
    sa.Column('Employee_Name', sa.Unicode(length=80), nullable=False),
    sa.Column('Labor_Category', sa.Unicode(length=30), nullable=False),
    sa.Column('CC_ID', sa.SmallInteger(), nullable=False),
    sa.Column('Resource_ID', sa.Integer(), nullable=True),
    sa.Column('Annual_Cost_EUR', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('Actual_Hours_Year', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('Max_Hours_Year', sa.Numeric(precision=8, scale=2), server_default='1776', nullable=False),
    sa.Column('Utilization_Rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Nominal_Rate_EUR_h', sa.Numeric(precision=10, scale=4), sa.Computed('CAST(Annual_Cost_EUR / NULLIF(COALESCE(Actual_Hours_Year, Max_Hours_Year), 0) AS NUMERIC(10, 4))', persisted=True), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Annual_Cost_EUR >= 0', name=op.f('CK_tbl_LaborResources_cost')),
    sa.CheckConstraint('Utilization_Rate IS NULL OR Utilization_Rate BETWEEN 0 AND 1.2', name=op.f('CK_tbl_LaborResources_utilization')),
    sa.ForeignKeyConstraint(['CC_ID'], ['tbl_CostCenters.CC_ID'], name=op.f('FK_tbl_LaborResources_CC_ID')),
    sa.ForeignKeyConstraint(['Resource_ID'], ['tbl_Resources.Resource_ID'], name=op.f('FK_tbl_LaborResources_Resource_ID')),
    sa.PrimaryKeyConstraint('Employee_ID', name=op.f('PK_tbl_LaborResources')),
    sa.UniqueConstraint('Employee_Code', name=op.f('UQ_tbl_LaborResources_Employee_Code'))
    )
    op.create_index(op.f('IX_tbl_LaborResources_CC_ID'), 'tbl_LaborResources', ['CC_ID'], unique=False)
    op.create_index(op.f('IX_tbl_LaborResources_Resource_ID'), 'tbl_LaborResources', ['Resource_ID'], unique=False)
    op.create_table('tbl_ResourceActivities',
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Resource_ID', sa.Integer(), nullable=False),
    sa.Column('Activity_ID', sa.Integer(), nullable=False),
    sa.Column('Share_Pct', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('Allocation_Basis', sa.Unicode(length=80), nullable=True),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Share_Pct > 0 AND Share_Pct <= 1', name=op.f('CK_tbl_ResourceActivities_share')),
    sa.ForeignKeyConstraint(['Activity_ID'], ['tbl_Activities.Activity_ID'], name=op.f('FK_tbl_ResourceActivities_Activity_ID')),
    sa.ForeignKeyConstraint(['Resource_ID'], ['tbl_Resources.Resource_ID'], name=op.f('FK_tbl_ResourceActivities_Resource_ID')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_ResourceActivities_Scenario_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Scenario_ID', 'Resource_ID', 'Activity_ID', name=op.f('PK_tbl_ResourceActivities'))
    )
    op.create_table('tbl_Machines',
    sa.Column('Machine_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Machine_Code', sa.String(length=15), nullable=False),
    sa.Column('Description', sa.Unicode(length=80), nullable=False),
    sa.Column('Category_Code', sa.String(length=5), nullable=False),
    sa.Column('CC_ID', sa.SmallInteger(), nullable=False),
    sa.Column('Resource_ID', sa.Integer(), nullable=True),
    sa.Column('Building_ID', sa.Integer(), nullable=True),
    sa.Column('Power_KW_Motor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('Power_KW_Thermal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('Power_KW_Measured', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('Clamp_Force_tn', sa.SmallInteger(), nullable=True),
    sa.Column('Year_Built', sa.SmallInteger(), nullable=True),
    sa.Column('Country_Origin', sa.Unicode(length=30), nullable=True),
    sa.Column('Acquisition_Cost_EUR', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('Residual_Value_EUR', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('Useful_Life_Years', sa.SmallInteger(), nullable=True),
    sa.Column('Maintenance_Cost_Year_EUR', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('Hours_Per_Day', sa.Numeric(precision=4, scale=1), server_default='16', nullable=False),
    sa.Column('Days_Per_Year', sa.SmallInteger(), server_default='222', nullable=False),
    sa.Column('Downtime_Pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Annual_Hours', sa.Numeric(precision=10, scale=1), sa.Computed('CAST(Hours_Per_Day * Days_Per_Year AS NUMERIC(10, 1))', persisted=True), nullable=False),
    sa.Column('Depreciation_Per_Hour', sa.Numeric(precision=12, scale=6), sa.Computed('CAST((Acquisition_Cost_EUR - Residual_Value_EUR) / NULLIF(Useful_Life_Years * Hours_Per_Day * Days_Per_Year, 0) AS NUMERIC(12, 6))', persisted=True), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Days_Per_Year > 0 AND Days_Per_Year <= 366', name=op.f('CK_tbl_Machines_days')),
    sa.CheckConstraint('Downtime_Pct IS NULL OR Downtime_Pct BETWEEN 0 AND 1', name=op.f('CK_tbl_Machines_downtime')),
    sa.CheckConstraint('Hours_Per_Day > 0 AND Hours_Per_Day <= 24', name=op.f('CK_tbl_Machines_hours')),
    sa.ForeignKeyConstraint(['Building_ID'], ['tbl_Buildings.Building_ID'], name=op.f('FK_tbl_Machines_Building_ID')),
    sa.ForeignKeyConstraint(['CC_ID'], ['tbl_CostCenters.CC_ID'], name=op.f('FK_tbl_Machines_CC_ID')),
    sa.ForeignKeyConstraint(['Category_Code'], ['tbl_MachineCategories.Category_Code'], name=op.f('FK_tbl_Machines_Category_Code')),
    sa.ForeignKeyConstraint(['Resource_ID'], ['tbl_Resources.Resource_ID'], name=op.f('FK_tbl_Machines_Resource_ID')),
    sa.PrimaryKeyConstraint('Machine_ID', name=op.f('PK_tbl_Machines')),
    sa.UniqueConstraint('Machine_Code', name=op.f('UQ_tbl_Machines_Machine_Code'))
    )
    op.create_index(op.f('IX_tbl_Machines_CC_ID'), 'tbl_Machines', ['CC_ID'], unique=False)
    op.create_index(op.f('IX_tbl_Machines_Category_Code'), 'tbl_Machines', ['Category_Code'], unique=False)
    op.create_index(op.f('IX_tbl_Machines_Resource_ID'), 'tbl_Machines', ['Resource_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_Machines_Resource_ID'), table_name='tbl_Machines')
    op.drop_index(op.f('IX_tbl_Machines_Category_Code'), table_name='tbl_Machines')
    op.drop_index(op.f('IX_tbl_Machines_CC_ID'), table_name='tbl_Machines')
    op.drop_table('tbl_Machines')
    op.drop_table('tbl_ResourceActivities')
    op.drop_index(op.f('IX_tbl_LaborResources_Resource_ID'), table_name='tbl_LaborResources')
    op.drop_index(op.f('IX_tbl_LaborResources_CC_ID'), table_name='tbl_LaborResources')
    op.drop_table('tbl_LaborResources')
    op.drop_index(op.f('IX_tbl_Buildings_Resource_ID'), table_name='tbl_Buildings')
    op.drop_index(op.f('IX_tbl_Buildings_CC_ID'), table_name='tbl_Buildings')
    op.drop_table('tbl_Buildings')
    op.drop_index(op.f('IX_tbl_Resources_CC_ID'), table_name='tbl_Resources')
    op.drop_table('tbl_Resources')
    # ### end Alembic commands ###
