"""01 lookups

Revision ID: 2fdee2eca88e
Revises: 
Create Date: 2026-09-30 21:59:59.452018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '2fdee2eca88e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_BSSG',
    sa.Column('BSSG_Code', sa.String(length=2), nullable=False),
    sa.Column('BSSG_Name', sa.Unicode(length=40), nullable=False),
    sa.Column('Sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('BSSG_Code', name=op.f('PK_tbl_BSSG'))
    )
    op.create_table('tbl_BaseMaterials',
    sa.Column('Material_Code', sa.String(length=5), nullable=False),
    sa.Column('Material_Name', sa.Unicode(length=40), nullable=False),
    sa.Column('Material_Family', sa.String(length=20), nullable=False),
    sa.Column('Is_Recyclable', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Default_Regrind_Recovery', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Default_Regrind_Value', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Material_Family IN ('THERMOPLASTIC','METAL','WOOD','COMPOSITE','OTHER')", name='material_family'),
    sa.CheckConstraint('Default_Regrind_Recovery BETWEEN 0 AND 1', name='regrind_recovery'),
    sa.CheckConstraint('Default_Regrind_Value BETWEEN 0 AND 1', name='regrind_value'),
    sa.PrimaryKeyConstraint('Material_Code', name=op.f('PK_tbl_BaseMaterials'))
    )
    op.create_table('tbl_GlobalDefaults',
    sa.Column('Parameter', sa.String(length=50), nullable=False),
    sa.Column('Value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('Unit', sa.Unicode(length=20), nullable=True),
    sa.Column('Description', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Parameter', name=op.f('PK_tbl_GlobalDefaults'))
    )
    op.create_table('tbl_ItemCodeRules',
    sa.Column('Prefix', sa.String(length=5), nullable=False),
    sa.Column('Description', sa.Unicode(length=60), nullable=False),
    sa.Column('Item_Type', sa.String(length=20), nullable=False),
    sa.Column('Material_Source', sa.String(length=10), server_default='LAMAPLAST', nullable=False),
    sa.Column('Zero_Cost', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('BOM_Role', sa.String(length=10), nullable=False),
    sa.Column('ABC_Component_Type', sa.String(length=20), nullable=True),
    sa.Column('Is_Regrind_Source', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Regrind_Value_Override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("BOM_Role IN ('INPUT','OUTPUT','BOTH')", name='bom_role'),
    sa.CheckConstraint("Item_Type IN ('RAW_MAT','AUXILIARY','PACKAGING','FG','FG_FASON','SF','COMPONENT','MOULD')", name='item_type'),
    sa.CheckConstraint("Material_Source IN ('LAMAPLAST','CUSTOMER')", name='material_source'),
    sa.PrimaryKeyConstraint('Prefix', name=op.f('PK_tbl_ItemCodeRules'))
    )
    op.create_table('tbl_MachineCategories',
    sa.Column('Category_Code', sa.String(length=5), nullable=False),
    sa.Column('Category_Name', sa.Unicode(length=40), nullable=False),
    sa.Column('Machine_Group', sa.String(length=10), server_default='INJECTION', nullable=False),
    sa.Column('Clamp_Force_Min_tn', sa.SmallInteger(), nullable=True),
    sa.Column('Clamp_Force_Max_tn', sa.SmallInteger(), nullable=True),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Machine_Group IN ('INJECTION','AUXILIARY','TOOLSHOP')", name='machine_group'),
    sa.PrimaryKeyConstraint('Category_Code', name=op.f('PK_tbl_MachineCategories'))
    )
    op.create_table('tbl_CommercialPillars',
    sa.Column('Pillar_Code', sa.String(length=10), nullable=False),
    sa.Column('Pillar_Name', sa.Unicode(length=60), nullable=False),
    sa.Column('BSSG_Code', sa.String(length=2), nullable=False),
    sa.Column('Sort_order', sa.SmallInteger(), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['BSSG_Code'], ['tbl_BSSG.BSSG_Code'], name=op.f('FK_tbl_CommercialPillars_BSSG_Code')),
    sa.PrimaryKeyConstraint('Pillar_Code', name=op.f('PK_tbl_CommercialPillars'))
    )
    op.create_index(op.f('IX_tbl_CommercialPillars_BSSG_Code'), 'tbl_CommercialPillars', ['BSSG_Code'], unique=False)
    op.create_table('tbl_ProductGroups',
    sa.Column('Group_Code', sa.String(length=15), nullable=False),
    sa.Column('Group_Name', sa.Unicode(length=80), nullable=False),
    sa.Column('Pillar_Code', sa.String(length=10), nullable=False),
    sa.Column('Sort_Order', sa.SmallInteger(), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Pillar_Code'], ['tbl_CommercialPillars.Pillar_Code'], name=op.f('FK_tbl_ProductGroups_Pillar_Code')),
    sa.PrimaryKeyConstraint('Group_Code', name=op.f('PK_tbl_ProductGroups'))
    )
    op.create_index(op.f('IX_tbl_ProductGroups_Pillar_Code'), 'tbl_ProductGroups', ['Pillar_Code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_ProductGroups_Pillar_Code'), table_name='tbl_ProductGroups')
    op.drop_table('tbl_ProductGroups')
    op.drop_index(op.f('IX_tbl_CommercialPillars_BSSG_Code'), table_name='tbl_CommercialPillars')
    op.drop_table('tbl_CommercialPillars')
    op.drop_table('tbl_MachineCategories')
    op.drop_table('tbl_ItemCodeRules')
    op.drop_table('tbl_GlobalDefaults')
    op.drop_table('tbl_BaseMaterials')
    op.drop_table('tbl_BSSG')
    # ### end Alembic commands ###
