"""02 org

Revision ID: 3656465f8799
Revises: 2fdee2eca88e
Create Date: 2026-10-03 22:04:56.856924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3656465f8799'
down_revision: Union[str, Sequence[str], None] = '2fdee2eca88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cost_centers',
    sa.Column('CC_ID', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('CC_Code', sa.String(length=5), nullable=False),
    sa.Column('CC_Name', sa.Unicode(length=50), nullable=False),
    sa.Column('Functional_Direction', sa.Unicode(length=20), nullable=False),
    sa.Column('CC_Type', sa.String(length=12), nullable=False),
    sa.Column('Is_Primary', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Allocation_Method', sa.Unicode(length=30), nullable=True),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("CC_Type IN ('PRODUCTION','SUPPORT','COMMERCIAL','OVERHEAD')", name='cc_type'),
    sa.PrimaryKeyConstraint('CC_ID', name=op.f('PK_tbl_cost_centers')),
    sa.UniqueConstraint('CC_Code', name=op.f('UQ_tbl_cost_centers_CC_Code'))
    )
    op.create_table('tbl_activity',
    sa.Column('Activity_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Activity_Code', sa.String(length=12), nullable=False),
    sa.Column('Activity_Name', sa.Unicode(length=60), nullable=False),
    sa.Column('CC_ID', sa.SmallInteger(), nullable=False),
    sa.Column('Activity_Level', sa.String(length=10), nullable=False),
    sa.Column('ABC_Role', sa.Unicode(length=25), nullable=False),
    sa.Column('Driver_Name', sa.Unicode(length=40), nullable=False),
    sa.Column('Driver_UoM', sa.Unicode(length=20), nullable=False),
    sa.Column('Status', sa.String(length=10), server_default='PENDING', nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Activity_Level IN ('UNIT','BATCH','PRODUCT','FACILITY')", name='activity_level'),
    sa.CheckConstraint("Status IN ('PENDING','CONFIRMED','MODIFIED','DELETED','NEW')", name='status'),
    sa.ForeignKeyConstraint(['CC_ID'], ['tbl_cost_centers.CC_ID'], name=op.f('FK_tbl_activity_CC_ID')),
    sa.PrimaryKeyConstraint('Activity_ID', name=op.f('PK_tbl_activity')),
    sa.UniqueConstraint('Activity_Code', name=op.f('UQ_tbl_activity_Activity_Code'))
    )
    op.create_index(op.f('IX_tbl_activity_CC_ID'), 'tbl_activity', ['CC_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_activity_CC_ID'), table_name='tbl_activity')
    op.drop_table('tbl_activity')
    op.drop_table('tbl_cost_centers')
    # ### end Alembic commands ###
