"""04 items

Revision ID: 98e5275731c4
Revises: b2f9db667327
Create Date: 2026-10-03 22:27:57.363916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '98e5275731c4'
down_revision: Union[str, Sequence[str], None] = 'b2f9db667327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Customers',
    sa.Column('Customer_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Customer_Code', sa.String(length=10), nullable=False),
    sa.Column('Customer_Name', sa.Unicode(length=100), nullable=False),
    sa.Column('Is_Internal', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Customer_ID', name=op.f('PK_tbl_Customers')),
    sa.UniqueConstraint('Customer_Code', name=op.f('UQ_tbl_Customers_Customer_Code'))
    )
    op.create_table('tbl_Items',
    sa.Column('Item_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Item_Code', sa.String(length=20), nullable=False),
    sa.Column('Item_Name', sa.Unicode(length=100), nullable=False),
    sa.Column('Item_Category_Prefix', sa.String(length=5), nullable=False),
    sa.Column('BSSG_Code', sa.String(length=2), nullable=True),
    sa.Column('Pillar_Code', sa.String(length=10), nullable=True),
    sa.Column('Group_Code', sa.String(length=15), nullable=True),
    sa.Column('Base_Material_Code', sa.String(length=5), nullable=True),
    sa.Column('Customer_ID', sa.Integer(), nullable=True),
    sa.Column('UoM', sa.Unicode(length=10), server_default='τεμ.', nullable=False),
    sa.Column('Weight_kg', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('Density_g_cm3', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('Fason_Base_Item_ID', sa.Integer(), nullable=True),
    sa.Column('Regrind_Value_Override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Is_Purchased', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Is_Produced', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('ERP_Code', sa.String(length=30), nullable=True),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('Fason_Base_Item_ID IS NULL OR Fason_Base_Item_ID <> Item_ID', name='fason_not_self'),
    sa.CheckConstraint('Weight_kg IS NULL OR Weight_kg >= 0', name='weight'),
    sa.ForeignKeyConstraint(['BSSG_Code'], ['tbl_BSSG.BSSG_Code'], name=op.f('FK_tbl_Items_BSSG_Code')),
    sa.ForeignKeyConstraint(['Base_Material_Code'], ['tbl_BaseMaterials.Material_Code'], name=op.f('FK_tbl_Items_Base_Material_Code')),
    sa.ForeignKeyConstraint(['Customer_ID'], ['tbl_Customers.Customer_ID'], name=op.f('FK_tbl_Items_Customer_ID')),
    sa.ForeignKeyConstraint(['Fason_Base_Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_Items_Fason_Base_Item_ID')),
    sa.ForeignKeyConstraint(['Group_Code'], ['tbl_ProductGroups.Group_Code'], name=op.f('FK_tbl_Items_Group_Code')),
    sa.ForeignKeyConstraint(['Item_Category_Prefix'], ['tbl_ItemCodeRules.Prefix'], name=op.f('FK_tbl_Items_Item_Category_Prefix')),
    sa.ForeignKeyConstraint(['Pillar_Code'], ['tbl_CommercialPillars.Pillar_Code'], name=op.f('FK_tbl_Items_Pillar_Code')),
    sa.PrimaryKeyConstraint('Item_ID', name=op.f('PK_tbl_Items')),
    sa.UniqueConstraint('Item_Code', name=op.f('UQ_tbl_Items_Item_Code'))
    )
    op.create_index(op.f('IX_tbl_Items_BSSG_Code'), 'tbl_Items', ['BSSG_Code'], unique=False)
    op.create_index(op.f('IX_tbl_Items_Customer_ID'), 'tbl_Items', ['Customer_ID'], unique=False)
    op.create_index(op.f('IX_tbl_Items_ERP_Code'), 'tbl_Items', ['ERP_Code'], unique=False)
    op.create_index(op.f('IX_tbl_Items_Group_Code'), 'tbl_Items', ['Group_Code'], unique=False)
    op.create_index(op.f('IX_tbl_Items_Item_Category_Prefix'), 'tbl_Items', ['Item_Category_Prefix'], unique=False)
    op.create_table('tbl_LogisticsUnits',
    sa.Column('LU_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Item_ID', sa.Integer(), nullable=False),
    sa.Column('LU_Level', sa.SmallInteger(), nullable=False),
    sa.Column('Description', sa.Unicode(length=60), nullable=True),
    sa.Column('Base_Units_Per_LU', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('Gross_Weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('Length_m', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('Width_m', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('Height_m', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('Volume_m3', sa.Numeric(precision=12, scale=6), sa.Computed('CAST(Length_m * Width_m * Height_m AS NUMERIC(12, 6))', persisted=True), nullable=True),
    sa.Column('Is_Informational', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint('LU_Level BETWEEN 1 AND 3', name='lu_level'),
    sa.ForeignKeyConstraint(['Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_LogisticsUnits_Item_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LU_ID', name=op.f('PK_tbl_LogisticsUnits')),
    sa.UniqueConstraint('Item_ID', 'LU_Level', name=op.f('UQ_tbl_LogisticsUnits_Item_ID'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_LogisticsUnits')
    op.drop_index(op.f('IX_tbl_Items_Item_Category_Prefix'), table_name='tbl_Items')
    op.drop_index(op.f('IX_tbl_Items_Group_Code'), table_name='tbl_Items')
    op.drop_index(op.f('IX_tbl_Items_ERP_Code'), table_name='tbl_Items')
    op.drop_index(op.f('IX_tbl_Items_Customer_ID'), table_name='tbl_Items')
    op.drop_index(op.f('IX_tbl_Items_BSSG_Code'), table_name='tbl_Items')
    op.drop_table('tbl_Items')
    op.drop_table('tbl_Customers')
    # ### end Alembic commands ###
