"""03 security_2

Revision ID: b2f9db667327
Revises: 46461e328f3c
Create Date: 2026-10-03 22:13:14.107178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'b2f9db667327'
down_revision: Union[str, Sequence[str], None] = '46461e328f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Users',
    sa.Column('User_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Full_Name', sa.Unicode(length=100), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Password_Hash', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.String(length=10), server_default='USER', nullable=False),
    sa.Column('Is_Active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Must_Change_Password', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Failed_Logins', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('Locked_Until', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Last_Login_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Role IN ('ADMIN','EXPERT','USER')", name='role'),
    sa.PrimaryKeyConstraint('User_ID', name=op.f('PK_tbl_Users')),
    sa.UniqueConstraint('Username', name=op.f('UQ_tbl_Users_Username'))
    )
    op.create_table('tbl_AuditLog',
    sa.Column('Audit_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Username', sa.String(length=50), nullable=True),
    sa.Column('Action', sa.String(length=15), nullable=False),
    sa.Column('Table_Name', sa.String(length=60), nullable=True),
    sa.Column('Record_Key', sa.String(length=60), nullable=True),
    sa.Column('Changes_JSON', sa.UnicodeText(), nullable=True),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.CheckConstraint("Action IN ('INSERT','UPDATE','DELETE','LOGIN','LOGIN_FAILED','LOCK','UNLOCK','COST_RUN')", name='action'),
    sa.ForeignKeyConstraint(['User_ID'], ['tbl_Users.User_ID'], name=op.f('FK_tbl_AuditLog_User_ID')),
    sa.PrimaryKeyConstraint('Audit_ID', name=op.f('PK_tbl_AuditLog'))
    )
    op.create_index('IX_tbl_AuditLog_at', 'tbl_AuditLog', ['At'], unique=False)
    op.create_index('IX_tbl_AuditLog_record', 'tbl_AuditLog', ['Table_Name', 'Record_Key'], unique=False)
    op.create_table('tbl_UserPermissions',
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Module', sa.String(length=20), nullable=False),
    sa.Column('Can_Edit', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Module IN ('ITEMS','PRICES','BOM','MOULDS','MACHINES','BUILDINGS','LABOR','COST_STRUCTURE','GL','DRIVERS','SCENARIOS')", name='module'),
    sa.ForeignKeyConstraint(['User_ID'], ['tbl_Users.User_ID'], name=op.f('FK_tbl_UserPermissions_User_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('User_ID', 'Module', name=op.f('PK_tbl_UserPermissions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_UserPermissions')
    op.drop_index('IX_tbl_AuditLog_record', table_name='tbl_AuditLog')
    op.drop_index('IX_tbl_AuditLog_at', table_name='tbl_AuditLog')
    op.drop_table('tbl_AuditLog')
    op.drop_table('tbl_Users')
    # ### end Alembic commands ###
