"""08 bom

Revision ID: d7a569fd643a
Revises: 023c018ffd88
Create Date: 2026-10-03 23:03:43.856536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'd7a569fd643a'
down_revision: Union[str, Sequence[str], None] = '023c018ffd88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_BOM',
    sa.Column('BOM_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Parent_Item_ID', sa.Integer(), nullable=False),
    sa.Column('BOM_Version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('Status', sa.String(length=10), server_default='DRAFT', nullable=False),
    sa.Column('BOM_Name', sa.Unicode(length=80), nullable=True),
    sa.Column('Valid_From', sa.Date(), nullable=True),
    sa.Column('Valid_To', sa.Date(), nullable=True),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Status IN ('DRAFT','ACTIVE','ARCHIVED')", name=op.f('CK_tbl_BOM_status')),
    sa.CheckConstraint('Valid_To IS NULL OR Valid_To >= Valid_From', name=op.f('CK_tbl_BOM_valid_range')),
    sa.ForeignKeyConstraint(['Parent_Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_BOM_Parent_Item_ID')),
    sa.PrimaryKeyConstraint('BOM_ID', name=op.f('PK_tbl_BOM')),
    sa.UniqueConstraint('Parent_Item_ID', 'BOM_Version', name=op.f('UQ_tbl_BOM_Parent_Item_ID'))
    )
    op.create_index(op.f('IX_tbl_BOM_Parent_Item_ID'), 'tbl_BOM', ['Parent_Item_ID'], unique=False)
    op.create_index('UX_tbl_BOM_one_active', 'tbl_BOM', ['Parent_Item_ID'], unique=True, mssql_where=sa.text("Status = 'ACTIVE'"))
    op.create_table('tbl_BOMLines',
    sa.Column('BOM_Line_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BOM_ID', sa.Integer(), nullable=False),
    sa.Column('Sequence', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('Component_Type', sa.String(length=20), nullable=False),
    sa.Column('Child_Item_ID', sa.Integer(), nullable=False),
    sa.Column('Qty', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('Scrap_Pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Is_Optional', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Component_Type IN ('RAW_MATERIAL','MASTERBATCH','ADDITIVE','PURCHASED','COMPONENT','SEMI_FINISHED','ASSEMBLY_FASON','PACKAGING_PRI','PACKAGING_SEC','PACKAGING_TER')", name=op.f('CK_tbl_BOMLines_component_type')),
    sa.CheckConstraint('Qty > 0', name=op.f('CK_tbl_BOMLines_qty')),
    sa.CheckConstraint('Scrap_Pct IS NULL OR Scrap_Pct BETWEEN 0 AND 1', name=op.f('CK_tbl_BOMLines_scrap')),
    sa.ForeignKeyConstraint(['BOM_ID'], ['tbl_BOM.BOM_ID'], name=op.f('FK_tbl_BOMLines_BOM_ID'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Child_Item_ID'], ['tbl_Items.Item_ID'], name=op.f('FK_tbl_BOMLines_Child_Item_ID')),
    sa.PrimaryKeyConstraint('BOM_Line_ID', name=op.f('PK_tbl_BOMLines'))
    )
    op.create_index(op.f('IX_tbl_BOMLines_BOM_ID'), 'tbl_BOMLines', ['BOM_ID'], unique=False)
    op.create_index(op.f('IX_tbl_BOMLines_Child_Item_ID'), 'tbl_BOMLines', ['Child_Item_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_BOMLines_Child_Item_ID'), table_name='tbl_BOMLines')
    op.drop_index(op.f('IX_tbl_BOMLines_BOM_ID'), table_name='tbl_BOMLines')
    op.drop_table('tbl_BOMLines')
    op.drop_index('UX_tbl_BOM_one_active', table_name='tbl_BOM', mssql_where=sa.text("Status = 'ACTIVE'"))
    op.drop_index(op.f('IX_tbl_BOM_Parent_Item_ID'), table_name='tbl_BOM')
    op.drop_table('tbl_BOM')
    # ### end Alembic commands ###
