"""09 ledger

Revision ID: deeaf1f973de
Revises: d7a569fd643a
Create Date: 2026-10-03 23:08:34.293966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'deeaf1f973de'
down_revision: Union[str, Sequence[str], None] = 'd7a569fd643a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_DriverValues',
    sa.Column('Driver_Value_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('Activity_ID', sa.Integer(), nullable=False),
    sa.Column('Driver_Quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('Is_Practical_Capacity', sa.Boolean(), nullable=True),
    sa.Column('Source', sa.String(length=12), server_default='MANUAL', nullable=False),
    sa.Column('Reason', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Source IN ('MANUAL','SOFTONE','EXCEL','CALCULATED')", name=op.f('CK_tbl_DriverValues_source')),
    sa.CheckConstraint('Driver_Quantity >= 0', name=op.f('CK_tbl_DriverValues_qty')),
    sa.ForeignKeyConstraint(['Activity_ID'], ['tbl_Activities.Activity_ID'], name=op.f('FK_tbl_DriverValues_Activity_ID')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_DriverValues_Scenario_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Driver_Value_ID', name=op.f('PK_tbl_DriverValues')),
    sa.UniqueConstraint('Scenario_ID', 'Activity_ID', name=op.f('UQ_tbl_DriverValues_Scenario_ID'))
    )
    op.create_index(op.f('IX_tbl_DriverValues_Activity_ID'), 'tbl_DriverValues', ['Activity_ID'], unique=False)
    op.create_table('tbl_GLFmeri',
    sa.Column('GL_Line_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Scenario_ID', sa.Integer(), nullable=False),
    sa.Column('GL_Account', sa.String(length=20), nullable=False),
    sa.Column('GL_Description', sa.Unicode(length=100), nullable=True),
    sa.Column('Total_Amount_EUR', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('Source', sa.String(length=12), server_default='MANUAL', nullable=False),
    sa.Column('Notes', sa.Unicode(length=200), nullable=True),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.CheckConstraint("Source IN ('MANUAL','SOFTONE','EXCEL','CALCULATED')", name=op.f('CK_tbl_GLFmeri_source')),
    sa.ForeignKeyConstraint(['Scenario_ID'], ['tbl_Scenarios.Scenario_ID'], name=op.f('FK_tbl_GLFmeri_Scenario_ID'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('GL_Line_ID', name=op.f('PK_tbl_GLFmeri')),
    sa.UniqueConstraint('Scenario_ID', 'GL_Account', name=op.f('UQ_tbl_GLFmeri_Scenario_ID'))
    )
    op.create_index(op.f('IX_tbl_GLFmeri_Scenario_ID'), 'tbl_GLFmeri', ['Scenario_ID'], unique=False)
    op.create_table('tbl_GLFmeriAllocations',
    sa.Column('GL_Alloc_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GL_Line_ID', sa.Integer(), nullable=False),
    sa.Column('CC_ID', sa.SmallInteger(), nullable=False),
    sa.Column('Resource_ID', sa.Integer(), nullable=True),
    sa.Column('Amount_EUR', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('Created_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('Created_By', sa.String(length=50), nullable=True),
    sa.Column('Updated_At', sa.DateTime().with_variant(mssql.DATETIME2(precision=0), 'mssql'), nullable=True),
    sa.Column('Updated_By', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['CC_ID'], ['tbl_CostCenters.CC_ID'], name=op.f('FK_tbl_GLFmeriAllocations_CC_ID')),
    sa.ForeignKeyConstraint(['GL_Line_ID'], ['tbl_GLFmeri.GL_Line_ID'], name=op.f('FK_tbl_GLFmeriAllocations_GL_Line_ID'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Resource_ID'], ['tbl_Resources.Resource_ID'], name=op.f('FK_tbl_GLFmeriAllocations_Resource_ID')),
    sa.PrimaryKeyConstraint('GL_Alloc_ID', name=op.f('PK_tbl_GLFmeriAllocations')),
    sa.UniqueConstraint('GL_Line_ID', 'CC_ID', 'Resource_ID', name=op.f('UQ_tbl_GLFmeriAllocations_GL_Line_ID'))
    )
    op.create_index(op.f('IX_tbl_GLFmeriAllocations_GL_Line_ID'), 'tbl_GLFmeriAllocations', ['GL_Line_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_tbl_GLFmeriAllocations_GL_Line_ID'), table_name='tbl_GLFmeriAllocations')
    op.drop_table('tbl_GLFmeriAllocations')
    op.drop_index(op.f('IX_tbl_GLFmeri_Scenario_ID'), table_name='tbl_GLFmeri')
    op.drop_table('tbl_GLFmeri')
    op.drop_index(op.f('IX_tbl_DriverValues_Activity_ID'), table_name='tbl_DriverValues')
    op.drop_table('tbl_DriverValues')
    # ### end Alembic commands ###
